FROM node:alpine

# ENV DOCKERIZE_VERSION v0.6.1

# RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
#     && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

WORKDIR /app

COPY package.json ./

RUN npm install

COPY ./ ./

# RUN chmod +x docker-entrypoint.sh

# ENTRYPOINT ./docker-entrypoint.sh

CMD [ "npm","run","start" ]

EXPOSE 3000